---
title: "Linear Models"
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
library(tidyverse)
library(p8105.datasets)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Examples

AirBnB

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(boro = neighbourhood_group,
         neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)

```

Fit a model for price as an outcome 

```{r}

fit = lm(price ~ stars + boro, data = nyc_airbnb)

```

Look at summaries


```{r}
summary(fit)
summary(fit)$coef
coef(fit)
# fitted.values(fit)
```

Look at better summaries...

```{r}

fit %>% 
  broom::tidy()

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)

```

Look at other summaries...
```{r}
fit %>% 
  broom::glance()

fit %>% 
  broom::glance() %>% 
  select(r.squared, adj.r.squared)
```

Be carefu with factor order...

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(boro = fct_infreq(boro),  # in order of frequency
         room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>% 
  broom::tidy()
```


## Diagnostics

Add residuals to dataset

```{r}
modelr::add_residuals(nyc_airbnb, fit)

modelr::add_predictions(nyc_airbnb, fit)


modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) + geom_boxplot()

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()

nyc_airbnb %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = stars, y = pred, color = boro)) + geom_point()

```


